---
language: cpp
os: linux
dist: bionic
compiler:
  - gcc
  - clang
arch:
  - amd64
  - ppc64le
  - arm64
script:
  - |
    # Build PINPOINT
    mkdir build && cd build
    cmake -DCMAKE_BUILD_TYPE=Release ..
    make -j"$(nproc)"
